# This file is a template, and might need editing before it works on your project.
# Official Java image. Look for the different tagged releases at
# https://hub.docker.com/r/library/java/tags/ . A Java image is not required
# but an image with a JVM speeds up the build a bit.
language: scala
scala:
    - 2.11.7

script:
    # Does the project build ?
    - sbt clean compile

notifications:
    email:
        - stenodyon@gmail.com
    irc:
        channels:
            - irc.crans.org#The_TD
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
        nick: tower_defense_ci
